version: "3.8"
services:
  api:
    build: .
    container_name: leve_saude_api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
